name: desafio1
services:
    php:
        build: .docker/php
        env_file: .env
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
    nginx:
        image: nginx
        env_file: .env
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - db
    db:
        image: mysql:8.1
        env_file: .env
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_HOST: '${DB_HOST}'
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_SSL_MODE: DISABLED

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        env_file: .env
        ports:
            - 8080:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions
    redis:
        image: redis:latest
        env_file: .env
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379

volumes:
    mysql-data: