name: desafio1
services:
    php:
        build: .docker/php
        env_file: .env.production
        ports:
            - 5173:5173
        volumes:
            - ./:/var/www:cached
    nginx:
        image: nginx
        env_file: .env.production
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - db
    db:
        image: mysql:8.1
        env_file: .env.production
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_HOST: '${DB_HOST}'
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_SSL_MODE: DISABLED

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        env_file: .env.production
        ports:
            - 8080:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions
    redis:
        image: redis:latest
        env_file: .env.production
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379

    laravel-queue-worker:
        build: .docker/php
        env_file: .env.production
        container_name: queue-worker
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        command: php artisan queue:work --sleep=3 --tries=3 --timeout=3600
        restart: always
        depends_on:
            - php
            - db
            - redis

    rabbitmq:
        image: rabbitmq:4-management
        env_file: .env.production
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

volumes:
    mysql-data:
    rabbitmq-data: